---
kind: pipeline
name: test

trigger:
  ref:
    - refs/heads/master # All pushes to master

    - refs/heads/drone # All pushes to yarn

    - refs/pull/*/* # All pull requests regardless of branch

    - refs/tags/* # Tags for releasing/etc

platform:
  os: linux
  arch: amd64

workspace:
  base: /

steps:
  - name: install-brew-hub then do stuff
    image: node:10.16.3
    pull: default
    commands:
      - git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
      - mkdir ~/.linuxbrew/bin
      - ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
      - eval $(~/.linuxbrew/bin/brew shellenv)
      - brew install hub
      - hub --help
      - bash sync.sh

