version: '3'
services:
  exemplar_app:
    build:  .
    # image:  flavioespinoza/docker-react-node:latest
    container_name: exemplar_app
    command: yarn start-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      PORT: "5000"
      NODE_ENV: "development"