# Base image
FROM node:10.16.3-alpine

COPY ./ /usr/app/

RUN apk update

COPY package.json /tmp/package.json
COPY yarn.lock /tmp/yarn.lock

# Install dependencies display warnings and errors only
RUN cd /tmp && yarn

RUN mkdir -p /usr/app && cp -a /tmp/node_modules /usr/app

WORKDIR /usr/app

# Build optimized React sources
RUN yarn run build

ENV NODE_ENV="production"

# Expose the port so host can have access
EXPOSE 80

CMD [ "yarn", "start-prod" ]