version: '3'
services:
  exemplar_dev:
    image: flavioespinoza/docker-react-node:latest
    container_name: exemplar_dev
    command: yarn start-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      PORT: "5000"
      NODE_ENV: "development"