# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
revisionHistoryLimit: 1
image:
  repository: https://cloud.docker.com/u/flavioespinoza/repository/docker/flavioespinoza/docker-react-node
  tag: v1
  pullPolicy: IfNotPresent
service:
  name: Node
  type: NodePort
  containerPort: 8080
  env: production
  